language: android

branches:
  only:
    - master

jdk:
  - oraclejdk7

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-android-m2repository
    - extra-google-m2repository
    - platform-tools
    - tools

env:
  matrix:
    - ANDROID_TARGET=android-15
    - ANDROID_TARGET=android-16
    - ANDROID_TARGET=android-17
    - ANDROID_TARGET=android-18
    - ANDROID_TARGET=android-19
    - ANDROID_TARGET=android-20
    - ANDROID_TARGET=android-21
    - ANDROID_TARGET=android-22
    - ANDROID_TARGET=android-23

before_install:
  - echo y | android update sdk --all --no-ui --force --filter build-tools-23.0.1

script:
  - ./gradlew build testDebug

after_success:
  - if [[ "$ANDROID_TARGET" == "android-23" ]]; then ./gradlew jacocoTestReport coveralls; fi

sudo: false

cache:
  directories:
    - $HOME/.gradle
