language: android

branches:
  only:
    - master

jdk:
  - oraclejdk7

android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-m2repository
    - extra-google-m2repository
    - platform-tools
    - tools

env:
  matrix:
    - ANDROID_TARGET=android-15
    - ANDROID_TARGET=android-16
    - ANDROID_TARGET=android-17
    - ANDROID_TARGET=android-18
    - ANDROID_TARGET=android-19
    - ANDROID_TARGET=android-20
    - ANDROID_TARGET=android-21
    - ANDROID_TARGET=android-22

script:
  - ./gradlew build testDebugUnitTest

sudo: false

cache:
  directories:
    - $HOME/.gradle