# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ShowsRage
email: m.gaetan89@gmail.com
description: >
  Android application to manage your SickRage/SickBeard installation.
baseurl: "ShowsRage" # the subpath of your site, e.g. /blog
url: "https://MGaetan89.github.io" # the base hostname & protocol for your site
sass:
  style: compressed

collections:
- help
- versions
