# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ShowsRage
email: m.gaetan89@gmail.com
description: >
  Android application to manage your SickRage/SickBeard installation.
baseurl: "/ShowsRage" # the subpath of your site, e.g. /blog
url: "https://MGaetan89.github.io" # the base hostname & protocol for your site
repository: MGaetan89/ShowsRage
sass:
  style: compressed
play_store:
  test: https://play.google.com/apps/testing/com.mgaetan89.showsrage
  url: https://play.google.com/store/apps/details?id=com.mgaetan89.showsrage
google_plus_community_url: https://plus.google.com/communities/116042659322358505108

collections:
- features
- help
- versions

gems:
- jekyll-github-metadata
- jekyll-seo-tag
